http:
  routers:
    ogt-app:
      rule: "PathPrefix(`/`)"
      service: ogt-app
      entryPoints:
        - web
  services:
    ogt-app:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9000"
