entryPoints:
  web:
    address: ":8080"
  metrics:
    address: ":8081"

api:
  dashboard: false

providers:
  file:
    filename: /etc/traefik/dynamic.yml

metrics:
  prometheus:
    entryPoint: metrics